# Generated by Django 2.1.2 on 2018-11-15 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20181115_1349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='defendant_sum',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='organization',
            name='plaintiff_sum',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
